name: gather_here
description: "여기로 모여라"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^7.1.0
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  flutter_secure_storage: ^5.0.2
  retrofit: ^4.2.0
  logger: any  #for logging purpose
  google_maps_flutter: ^2.9.0
  easy_debounce: ^2.0.3 #for debounce and throttle
  geolocator: ^13.0.1
  json_annotation: ^4.9.0
  image_picker: ^0.8.7+4
  web_socket_channel: ^3.0.1
  intl: ^0.19.0
  flutter_localization: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^7.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets:
    - asset/img/
  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/fonts/Pretendard-Black.otf
          weight: 900
        - asset: asset/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: asset/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: asset/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: asset/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: asset/fonts/Pretendard-Light.otf
          weight: 300
        - asset: asset/fonts/Pretendard-Thin.otf
          weight: 100